version: '3.1'

services:
  api:
    image: "node:12"
    restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DB_ENGINE=${DB_ENGINE}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_USERNAME}
    volumes:
      - ./api:/home/node/app
    ports:
      - ${PORT}
    command: "npm start"
    depends_on:
      - database