version: '3.1'

services:
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: cashforce
    volumes: 
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
