const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/routes/routes.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "CashForce API",
        description: "Documentation automatically generated by the <b>swagger.autogen</b> module."
    },
    securityDefinitions: {
        api_key: {
            type: "token",
            name: "token",
            in: "header"
        }
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name":"Auth",
            "description":"Autenticação da API"
        },
        {
            "name": "Orders",
            "description": "Endpoints"
        }
    ],
}

swaggerAutogen(outputFile, endpointsFiles,doc)